# Generated by Django 2.2.17 on 2021-01-21 13:42

import uuid

import django.contrib.postgres.fields.jsonb
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("keycloak_data", django.contrib.postgres.fields.jsonb.JSONField(default={"groups": {}})),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title", verbose_name="slug"
                    ),
                ),
                ("secret_token", models.CharField(blank=True, max_length=300)),
                ("on_trial", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
