# Generated by Django 2.2.19 on 2021-03-10 13:32

from django.db import migrations, models

import organization.models.organization


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="avatar_image",
            field=models.FileField(
                default=organization.models.organization.get_default_avatar_image, null=True, upload_to=""
            ),
        ),
    ]
