# Generated by Django 2.2.22 on 2021-05-06 19:12

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

import organization.models.organization


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_organization_avatar_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="avatar_image",
            field=models.FileField(
                blank=True, default=organization.models.organization.get_default_avatar_image, null=True, upload_to=""
            ),
        ),
        migrations.CreateModel(
            name="OrganizationMemberInvitation",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("accepted", models.NullBooleanField()),
                ("expired", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.Organization"),
                ),
            ],
            options={
                "unique_together": {("organization", "email")},
            },
        ),
    ]
